name: finology
description: A new Flutter project.

publish_to: 'none' 

version: 1.1.0+10

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.14.0
  cupertino_icons: ^1.0.5
  flutter_credit_card:
    path: flutter_credit_card-master/
  fluttertoast: ^8.2.2
  animate_do: ^3.0.2
  animations: ^2.0.7
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.5
  http: ^1.0.0
  intl: ^0.18.1
  lottie: ^2.3.2
  page_transition: ^2.0.9
  percent_indicator: ^4.2.3
  pie_chart: ^5.3.2
  pin_code_fields: ^7.4.0
  dio: ^4.0.6
  get: ^4.6.5
  provider: ^6.0.5
  flutter_platform_widgets: ^3.3.5
  readmore: ^2.2.0
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  carousel_slider: ^4.2.1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.2.8
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.3.3
  json_serializable: ^6.7.1

flutter_icons:
  android: true
  ios: true
  image_path: "/Kabak_logo.jpg"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/jsonImage/
    - lib/screen/Widgets/country_all_picker/raw/all_country_details.json
    - lib/screen/Widgets/country_all_picker/flags/

 